/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;
import BLL.UserManager;
import DAL.DAO.User;
import UI.RegistrationForm;
import UI.MenuForm;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import UI.HomePage;

public class LoginForm extends javax.swing.JFrame {

    /**
     * Creates new form LoginForm
     */
    public LoginForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        userNameTextField = new javax.swing.JTextField();
        loginButton = new javax.swing.JButton();
        registerhereButton = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        homepageButton = new javax.swing.JButton();
        passwordTextField2 = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setText("User Name");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(260, 128, 102, 14);

        jLabel2.setText("Password");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(260, 166, 102, 14);
        getContentPane().add(userNameTextField);
        userNameTextField.setBounds(428, 125, 210, 30);

        loginButton.setText("Login");
        loginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginButtonActionPerformed(evt);
            }
        });
        getContentPane().add(loginButton);
        loginButton.setBounds(430, 230, 141, 37);

        registerhereButton.setText("Register here!");
        registerhereButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerhereButtonActionPerformed(evt);
            }
        });
        getContentPane().add(registerhereButton);
        registerhereButton.setBounds(430, 290, 141, 35);

        jLabel4.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel4.setText("Login Form");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(252, 69, 118, 38);

        homepageButton.setText("Homepage");
        homepageButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homepageButtonActionPerformed(evt);
            }
        });
        getContentPane().add(homepageButton);
        homepageButton.setBounds(797, 11, 93, 40);
        getContentPane().add(passwordTextField2);
        passwordTextField2.setBounds(430, 170, 210, 30);

        setSize(new java.awt.Dimension(916, 539));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void registerhereButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerhereButtonActionPerformed
        
        RegistrationForm Info = new RegistrationForm();
        Info.setVisible(true);
        dispose();
        
    }//GEN-LAST:event_registerhereButtonActionPerformed

    private void loginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginButtonActionPerformed
        
      
       int i; 
       String user,pass;
       user=userNameTextField.getText();
       pass=passwordTextField2.getText();
       if(user.equals("admin") && pass.equals("password"))
       {
           
               
                MenuForm Info = new MenuForm();
                 Info.setVisible(true);
                 dispose();
                
               
           }
       else{
       for(i = 0;i<UserManager.userList.size(); i++){
             
          
           if( UserManager.userList.get(i).getUserName().equalsIgnoreCase(userNameTextField.getText()) && UserManager.userList.get(i).getPassword().equalsIgnoreCase(passwordTextField2.getText())){
                 MenuForm Info = new MenuForm();
                 Info.setVisible(true);
                 dispose();
                 break;
           }
          
       }      
   
      if(UserManager.userList.size()==i){
           JOptionPane.showMessageDialog(null, "User Name And Password Not Match");
       }
       }
    }//GEN-LAST:event_loginButtonActionPerformed

    private void homepageButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homepageButtonActionPerformed
        // TODO add your handling code here:
        HomePage Info = new HomePage();
        Info.setVisible(true);
        dispose();
    }//GEN-LAST:event_homepageButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton homepageButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JButton loginButton;
    private javax.swing.JPasswordField passwordTextField2;
    private javax.swing.JButton registerhereButton;
    private javax.swing.JTextField userNameTextField;
    // End of variables declaration//GEN-END:variables
}
